version: "3.8"

services:
  # JobGen API
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env # local development .env (DO NOT COMMIT)
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DB_NAME=${DB_NAME:-jobgen}
      - JWT_SECRET=${JWT_SECRET}
      - ACCESS_TOKEN_DURATION=${ACCESS_TOKEN_DURATION:-24h}
      - REFRESH_TOKEN_DURATION=${REFRESH_TOKEN_DURATION:-168h}
      - PORT=${PORT:-8080}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - mongo
    restart: unless-stopped

  # MongoDB Database
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  # MongoDB Express (Database UI)
  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER:-mongo}
      - ME_CONFIG_MONGODB_PORT=${ME_CONFIG_MONGODB_PORT:-27017}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo_data:
